INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (81264975, 'HSBC UK', 'Aid for All Crisis Response', 'S1');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (10001001, 'Lloyds', 'Aid for All International', 'S4');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (20011002, 'Revolut', 'AFA Crisis Donations', 'S5');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (30021003, 'Barclays', 'AFAResponse', 'S4');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (40031004, 'Barclays', 'Aid for All Crisis Response', 'S5');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (50041005, 'CIBC', 'Rapid Response AFA International', 'S6');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (60051006, 'Wells Fargo', 'Aid for All', 'S2');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (70061007, 'Wells Fargo', 'AFA International ', 'S2');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (80071008, 'First bank', 'AFA International Donations', 'S3');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (90081009, 'Gtbank', 'Aid for All  humanitarian organization', 'S1');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (10091010, 'HSBC UK', 'AFA International Org.', 'S7');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (11101011, 'Bank of America', 'Aid for All Organization', 'S3');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (12111112, 'Bank of Montreal', 'AFA donations', 'S3');
INSERT INTO "humanitarianOrg".account (accountid, bankname, accountname, accountmanagerid) VALUES (13121113, 'Lloyds', 'Aid for All crisis Organization', 'S4');
