INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S1', 'John Doe', 'Account Manager', 5000);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S41', 'Beyonce Knowles', 'Cleaner', 1000);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S10', 'Peter Joseph', 'Crisis Coordinator', 3500);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S13', 'Jonathan Vincent', 'Crisis Coordinator', 2900);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S90', 'Burna Boy', 'Volunteer', 0);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S32', 'Lionel Messi', 'Volunteer', 0);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S15', 'James St Patrick', 'Crisis Coordinator', 6800);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S16', 'Peter Obi', 'Crisis Coordinator', 700);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S33', 'Ginger Baker', 'Volunteer', 0);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S2', 'Mai Atafo', 'Account Manager', 5000);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S3', 'Barack Obama', 'Account Manager', 3400);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S4', 'Emily Rodden', 'Account Manager', 9000);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S88', 'Ayokunle McMath', 'Analyst', 1200);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S5', 'Jack Reacher', 'Account Manager', 4500);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S6', 'Amos Leye', 'Account Manager', 6500);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S56', 'Enoch Adeboye', 'Analyst', 9000);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S7', 'Helen Adebola', 'Account Manager', 8000);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S8', 'Adamu Garba', 'Crisis Coordinator', 750);
INSERT INTO "humanitarianOrg".staff (staffid, staffname, staffrole, staffsalary) VALUES ('S9', 'Paul Blake', 'Crisis Coordinator', 4300);
